In [6]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load the Wine dataset
wine = datasets.load_wine()
X, y = wine.data, wine.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the SVM classifier with One-vs-One strategy
svm_ovo = SVC(decision_function_shape='ovo')
svm_ovo.fit(X_train, y_train)

# Predict and evaluate the One-vs-One model
y_pred_ovo = svm_ovo.predict(X_test)
print("One-vs-One Accuracy:", accuracy_score(y_test, y_pred_ovo))

One-vs-One Accuracy: 0.7592592592592593


In [2]:
X.shape

(178, 13)

In [3]:
y.shape

(178,)

In [4]:
X_train.shape

(124, 13)

In [5]:
X_test.shape

(54, 13)

In [6]:
y_train.shape

(124,)

In [7]:
y_test.shape

(54,)

In [3]:
X[2]

array([1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
       3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
       1.185e+03])

In [11]:
y_pred_ovo.shape

(54,)

In [4]:
y_pred_ovo

array([0, 0, 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2,
       1, 0, 2, 1, 1, 0, 1, 0, 0, 1])

In [7]:
import numpy as np

test = np.tile(np.arange(0, 50), (50, 2, 200))
print(test.shape)
print(test)

test_X = test.transpose(2, 1, 0).reshape((-1, 50))
print(test_X.shape)
print(test_X)
print(test_X.flatten())

(50, 2, 10000)
[[[ 0  1  2 ... 47 48 49]
  [ 0  1  2 ... 47 48 49]]

 [[ 0  1  2 ... 47 48 49]
  [ 0  1  2 ... 47 48 49]]

 [[ 0  1  2 ... 47 48 49]
  [ 0  1  2 ... 47 48 49]]

 ...

 [[ 0  1  2 ... 47 48 49]
  [ 0  1  2 ... 47 48 49]]

 [[ 0  1  2 ... 47 48 49]
  [ 0  1  2 ... 47 48 49]]

 [[ 0  1  2 ... 47 48 49]
  [ 0  1  2 ... 47 48 49]]]
(20000, 50)
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 1  1  1 ...  1  1  1]
 ...
 [48 48 48 ... 48 48 48]
 [49 49 49 ... 49 49 49]
 [49 49 49 ... 49 49 49]]
[ 0  0  0 ... 49 49 49]


In [8]:
toy_response = np.array([[[5, 3, 2, 7], [4, 2, 5, 3]],
                         [[5, 5, 2, 2], [2, 1, 2, 8]],
                         [[3, 1, 2, 1], [7, 8, 4, 9]]])
print(toy_response)
print(toy_response.shape) # n_neurons x n_bins x n_trials

X_toy = toy_response.transpose(2, 1, 0).reshape((-1, 3))
print(X_toy)
print(X_toy.shape)

[[[5 3 2 7]
  [4 2 5 3]]

 [[5 5 2 2]
  [2 1 2 8]]

 [[3 1 2 1]
  [7 8 4 9]]]
(3, 2, 4)
[[5 5 3]
 [4 2 7]
 [3 5 1]
 [2 1 8]
 [2 2 2]
 [5 2 4]
 [7 2 1]
 [3 8 9]]
(8, 3)


In [9]:
y_response = np.array([[[0, 9, 0, 0], [1, 1, 1, 1]],
                       [[0, 9, 0, 0], [1, 1, 1, 1]],
                       [[0, 9, 0, 0], [1, 1, 1, 1]]])
y_toy = y_response.transpose(2, 1, 0).reshape((-1, 3))
print(y_toy)

[[0 0 0]
 [1 1 1]
 [9 9 9]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [ ]:
y_toy.flatten()